<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap | Preemptly</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #334155;
						background-color: #FAFAFA;
						margin: 0;
						padding: 40px 20px;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #ffffff;
						padding: 40px;
						border-radius: 24px;
						box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.05);
						border: 1px solid #f1f5f9;
					}
					header {
						margin-bottom: 40px;
						border-bottom: 2px solid #f1f5f9;
						padding-bottom: 30px;
						display: flex;
						justify-content: space-between;
						align-items: center;
					}
					.logo-area {
						display: flex;
						align-items: center;
						gap: 12px;
					}
					.logo-icon {
						width: 40px;
						height: 40px;
						background-color: #5a8c12;
						border-radius: 10px;
						display: flex;
						align-items: center;
						justify-content: center;
						color: white;
						font-weight: 800;
						font-size: 20px;
					}
					h1 {
						font-size: 24px;
						font-weight: 800;
						color: #0f172a;
						margin: 0;
						letter-spacing: -0.025em;
					}
					p.description {
						color: #64748b;
						font-size: 14px;
						line-height: 1.6;
						margin-top: 8px;
					}
					.stats {
						background: #f8fafc;
						padding: 12px 20px;
						border-radius: 12px;
						font-size: 13px;
						font-weight: 600;
						color: #475569;
						border: 1px solid #e2e8f0;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						padding: 16px;
						font-size: 12px;
						text-transform: uppercase;
						letter-spacing: 0.1em;
						color: #94a3b8;
						border-bottom: 1px solid #f1f5f9;
					}
					td {
						padding: 16px;
						font-size: 14px;
						border-bottom: 1px solid #f8fafc;
						color: #1e293b;
					}
					tr:hover td {
						background-color: #f8fafc;
					}
					.url-link {
						color: #5a8c12;
						text-decoration: none;
						font-weight: 600;
					}
					.url-link:hover {
						text-decoration: underline;
					}
					.priority-badge {
						display: inline-block;
						padding: 4px 10px;
						border-radius: 6px;
						font-size: 12px;
						font-weight: 700;
						background: #f1f5f9;
						color: #475569;
					}
					.priority-high {
						background: #ecfdf5;
						color: #059669;
					}
					footer {
						margin-top: 40px;
						text-align: center;
						font-size: 12px;
						color: #94a3b8;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<header>
						<div class="logo-area">
							<div class="logo-icon">
								<img src="/preemptly-mascot.png" style="width: 100%; height: 100%; object-fit: cover;" />
							</div>
							<div>
								<h1>Preemptly Sitemap</h1>
								<p class="description">Index of all publicly accessible pages on bepreemptly.com</p>
							</div>
						</div>
						<div class="stats">
							Total URLs: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
						</div>
					</header>
					<table>
						<thead>
							<tr>
								<th width="65%">URL Path</th>
								<th width="15%">Priority</th>
								<th width="20%">Updated</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<a class="url-link">
											<xsl:attribute name="href">
												<xsl:value-of select="sitemap:loc"/>
											</xsl:attribute>
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<span>
											<xsl:attribute name="class">
												<xsl:choose>
													<xsl:when test="sitemap:priority &gt; 0.7">priority-badge priority-high</xsl:when>
													<xsl:otherwise>priority-badge</xsl:otherwise>
												</xsl:choose>
											</xsl:attribute>
											<xsl:value-of select="sitemap:priority * 100"/>%
										</span>
									</td>
									<td>
										<xsl:value-of select="sitemap:lastmod"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>
					<footer>
						Generated by Preemptly Visibility Engine | 2026
					</footer>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
